version: '3'
services:
  nestjs-app:
    image: nestjs-back4app # Название образа, которое будет создано при сборке Docker-образа
    ports:
      - "49161:3000" # Проброс портов - левая часть: порт хоста, правая часть: порт контейнера
